version: 2
updates:
  # Ruby dependencies
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    groups:
      development-dependencies:
        patterns:
          - "rspec*"
          - "factory_bot*"
          - "capybara"
          - "selenium-webdriver"
          - "webdrivers"
          - "webmock"
          - "bullet"
      linting-dependencies:
        patterns:
          - "rubocop*"
          - "brakeman"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    
  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"