x-app: &x-app
  build:
    context: .
    dockerfile: Dockerfile.dev
  volumes:
    - .:/app
  environment:
    PORT: 3000
    HOST: localhost

services:
  app:
    <<: *x-app
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rdbg --open=vscode --nonstop -c -- bin/rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
    tty: true
    stdin_open: true
    environment:
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub

  tailwind:
    <<: *x-app
    command: bin/rails tailwindcss:watch
    tty: true
    stdin_open: true
    depends_on:
      - db

  solid_queue:
    <<: *x-app
    command: bundle exec rake solid_queue:start
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "4432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always

  chrome:
    image: seleniarm/standalone-chromium
    shm_size: 2g
    ports:
      - 4444:4444
volumes:
  postgres_volume:

