version: '3.8'

x-app: &x-app
  build:
    context: .
  volumes:
    - .:/app

services:
  app:
    <<: *x-app
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rdbg --open=vscode --nonstop -c -- bin/rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - sidekiq
      - chrome
    tty: true
    stdin_open: true
    environment:
      PORT: 3000
      HOST: localhost
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
      REDIS_URL: redis://redis:6379
  tailwind:
    <<: *x-app
    command: bin/rails tailwindcss:watch
    tty: true
    stdin_open: true
    depends_on:
      - db


  sidekiq:
    <<: *x-app
    environment:
      REDISTOGO_URL: redis://redis:6379
      REDIS_PROVIDER: REDISTOGO_URL
    command: ["./bin/bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
    depends_on:
      - db
      - redis

  redis:
    image: redis:7.2-rc
    command: ["redis-server"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "4432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always

  chrome:
    image: seleniarm/standalone-chromium
    shm_size: 2g
    ports:
      - 4444:4444
volumes:
  postgres_volume:
  redis-data:

