default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: db

development:
  primary:
    <<: *default
    database: app_development
  cache:
    <<: *default
    database: cache_development
  queue:
    <<: *default
    database: queue_development

test:
  primary:
    adapter: sqlite3
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    timeout: 5000
    database: storage/test.primary.sqlite3
  cache:
    adapter: sqlite3
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    timeout: 5000
    database: storage/test.cache.sqlite3
  queue:
    adapter: sqlite3
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    timeout: 5000
    database: storage/test.queue.sqlite3

staging:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *default
    url: <%= ENV['CACHE_DATABASE_URL'] %>
  queue:
    <<: *default
    url: <%= ENV['QUEUE_DATABASE_URL'] %>

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *default
    url: <%= ENV['CACHE_DATABASE_URL'] %>
  queue:
    <<: *default
    url: <%= ENV['QUEUE_DATABASE_URL'] %>
