default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: db

development:
  primary:
    <<: *default
    database: app_development
  cache:
    <<: *default
    database: cache_development
  queue:
    <<: *default
    database: queue_development

test:
  primary:
    <<: *default
    database: app_test
    <% if ENV['DATABASE_URL'].present? %>
    url: <%= ENV['DATABASE_URL'] %>
    <% end %>
  cache:
    <<: *default
    database: cache_test
    <% if ENV['DATABASE_URL'].present? %>
    url: <%= ENV['DATABASE_URL'].sub(/app_base_test/, 'cache_test') %>
    <% end %>
  queue:
    <<: *default
    database: queue_test
    <% if ENV['DATABASE_URL'].present? %>
    url: <%= ENV['DATABASE_URL'].sub(/app_base_test/, 'queue_test') %>
    <% end %>

staging:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *default
    url: <%= ENV['CACHE_DATABASE_URL'] %>
  queue:
    <<: *default
    url: <%= ENV['QUEUE_DATABASE_URL'] %>

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *default
    url: <%= ENV['CACHE_DATABASE_URL'] %>
  queue:
    <<: *default
    url: <%= ENV['QUEUE_DATABASE_URL'] %>
