default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: app_development
    username: postgres
    password: password
    host: db
  cache:
    <<: *default
    database: cache_development
    username: postgres
    password: password
    host: db
  queue:
    <<: *default
    database: queue_development
    username: postgres
    password: password
    host: db

test:
  primary:
    <<: *default
    database: app_test
  cache:
    <<: *default
    database: cache_test
  queue:
    <<: *default
    database: queue_test

staging:
  primary:
    <<: *default
    database: app_staging
    username: postgres
    password: <%= ENV["DATABASE_PASSWORD"] %>
    host: /cloudsql/workshop-app-base:asia-northeast1:app-base
  cache:
    <<: *default
    database: cache_staging
    username: postgres
    password: <%= ENV["DATABASE_PASSWORD"] %>
    host: /cloudsql/workshop-app-base:asia-northeast1:app-base
  queue:
    <<: *default
    database: queue_staging
    username: postgres
    password: <%= ENV["DATABASE_PASSWORD"] %>
    host: /cloudsql/workshop-app-base:asia-northeast1:app-base

production:
  primary:
    <<: *default
    database: app_production
    username: postgres
    password: <%= ENV["DATABASE_PASSWORD"] %>
    host: /cloudsql/workshop-app-base:asia-northeast1:app-base
  cache:
    <<: *default
    database: cache_production
    username: postgres
    password: <%= ENV["DATABASE_PASSWORD"] %>
    host: /cloudsql/workshop-app-base:asia-northeast1:app-base
  queue:
    <<: *default
    database: queue_production
    username: postgres
    password: <%= ENV["DATABASE_PASSWORD"] %>
    host: /cloudsql/workshop-app-base:asia-northeast1:app-base