name: Build & Deploy Application

# このワークフローは継続的デプロイ専用
# インフラセットアップは別のワークフロー（setup-infrastructure.yml）で実行

# Required GitHub Secrets:
# - AWS_ROLE_ARN: ARN of the IAM role for OIDC authentication
# - AWS_REGION: AWS region (e.g., ap-northeast-1)
# - AWS_ACCOUNT_ID: AWS account ID
# - SLACK_BOT_TOKEN: Slack bot token (optional)
# - SLACK_CHANNEL_ID: Slack channel ID (optional)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write     # OIDC を使うなら必須
  contents: read

jobs:
  # アプリケーションのビルド・継続的デプロイ
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # テストワークフローの実行を待つ
      - name: Wait for test workflow
        uses: lewagon/wait-on-check-action@v1.4.0
        with:
          ref: ${{ github.ref }}
          check-name: 'test'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Wait for docker-build workflow
        uses: lewagon/wait-on-check-action@v1.4.0
        with:
          ref: ${{ github.ref }}
          check-name: 'docker-build'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # ECRリポジトリの存在確認と自動作成
      - name: Ensure ECR repository exists
        env:
          REPO: ${{ github.event.repository.name }}
        run: |
          echo "🔍 Checking if ECR repository exists: $REPO"
          
          if aws ecr describe-repositories --repository-names "$REPO" >/dev/null 2>&1; then
            echo "✅ ECR repository already exists: $REPO"
          else
            echo "📦 Creating ECR repository: $REPO"
            aws ecr create-repository \
              --repository-name "$REPO" \
              --image-scanning-configuration scanOnPush=true \
              --encryption-configuration encryptionType=AES256
            
            echo "✅ ECR repository created successfully: $REPO"
          fi

      - name: Build & Push image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPO:     ${{ github.event.repository.name }}
          TAG:      ${{ github.sha }}
        run: |
          echo "🐳 Building Docker image with multiple tags..."
          docker build -t $REGISTRY/$REPO:$TAG -t $REGISTRY/$REPO:latest .
          
          echo "📤 Pushing images to ECR..."
          docker push   $REGISTRY/$REPO:$TAG
          docker push   $REGISTRY/$REPO:latest
          
          echo "✅ Successfully pushed:"
          echo "  - $REGISTRY/$REPO:$TAG"
          echo "  - $REGISTRY/$REPO:latest"
          
          # Use latest tag for ECS deployment to avoid unnecessary task definition revisions
          # Comment out the next line and uncomment the line after if you want to use commit-specific tags
          echo "IMAGE_URI=$REGISTRY/$REPO:latest" >> $GITHUB_ENV
          # echo "IMAGE_URI=$REGISTRY/$REPO:$TAG" >> $GITHUB_ENV
          
          echo "✅ Docker image URI set for deployment: $REGISTRY/$REPO:latest"

      # インフラ存在確認
      - name: Check if infrastructure exists
        id: check-infra
        run: |
          echo "🔍 Checking if infrastructure exists..."
          
          INFRA_STACK_NAME="${{ github.event.repository.name }}-prod-infra"
          
          if aws cloudformation describe-stacks --stack-name $INFRA_STACK_NAME >/dev/null 2>&1; then
            echo "✅ Infrastructure stack exists: $INFRA_STACK_NAME"
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "infra-stack-name=$INFRA_STACK_NAME" >> $GITHUB_OUTPUT
          else
            echo "❌ Infrastructure stack not found: $INFRA_STACK_NAME"
            echo "Please run 'Setup Infrastructure (Manual Only)' workflow first"
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "::warning::Infrastructure not found. Deployment will be skipped."
            echo "📋 Next steps:"
            echo "1. Run 'Setup Infrastructure (Manual Only)' workflow from Actions tab"
            echo "2. Push code again to trigger automatic deployment"
          fi

      # アプリケーションデプロイ（分離されたテンプレートを使用）
      - name: Deploy Application
        # インフラが存在する場合のみ実行
        if: ${{ steps.check-infra.outputs.exists == 'true' }}
        run: |
          echo "🚀 Deploying application with separated template..."
          
          # Deploy with latest tag to minimize unnecessary ECS task definition revisions
          # Same ImageUri (latest tag) will not trigger new task definition revision
          aws cloudformation deploy \
            --template-file infra/app-deploy.yaml \
            --stack-name ${{ github.event.repository.name }}-app \
            --parameter-overrides \
              AppName=${{ github.event.repository.name }} \
              ImageUri=$IMAGE_URI \
              InfraStackName=${{ steps.check-infra.outputs.infra-stack-name }} \
            --capabilities CAPABILITY_IAM
          
          echo "✅ Application deployment completed"

      - name: Wait for ECS service stability
        if: ${{ steps.check-infra.outputs.exists == 'true' }}
        run: |
          echo "⏳ Waiting for ECS service to be stable..."
          aws ecs wait services-stable \
            --cluster workshop-app-prod-cluster \
            --services ${{ github.event.repository.name }}-service
          
          echo "✅ Service is now stable"
 
      # Slack notification
      - name: Notify Slack on success
        if: ${{ success() && steps.check-infra.outputs.exists == 'true' && env.SLACK_BOT_TOKEN != '' }}
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "ECR Push Success: ${{ github.repository }}"
            attachments:
              - color: "good"
                fields:
                  - title: "Image"
                    value: "${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}:${{ github.sha }}"
                    short: true
                  - title: "Branch"
                    value: "${{ github.ref_name }}",
                    short: true

      - name: Notify Slack on failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "ECR Push Failed: ${{ github.repository }}"
            attachments:
              - color: "danger"
                fields:
                  - title: "Status"
                    value: "Failed ❌"
                    short: true
                  - title: "Branch"
                    value: "${{ github.ref_name }}"
                    short: true
                  - title: "Details"
                    value: "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View workflow run>"