
name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup docker
      shell: bash
      run: |
        docker-compose build
        docker-compose run app bundle install
        docker-compose run app bundle exec rails assets:precompile
        docker-compose up -d
        docker-compose exec -T app bundle exec rails db:create
    - name: Run rubocop
      shell: bash
      run: |
        docker-compose exec -T app bundle exec rubocop
    - name: Run rspec
      shell: bash
      run: |
        docker-compose exec -T app bundle exec rspec
    - name: Notify deployment
      uses: 8398a7/action-slack@v3.8.0
      with:
        status: ${{ job.status }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true