
name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Post Slack Message
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "AppBase test started (In Progress)",
              "attachments": [
                {
                  "pretext": "Test started",
                  "color": "ffc107",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "In Progress"
                    }
                  ]
                }
              ]
            }
      - name: Setup Rails
        shell: bash
        run: |
          gem install bundler -v 2.6.8
          bundle config set --local path 'vendor/bundle'
          bundle install
          bin/rails db:create
      - name: Run brakeman
        shell: bash
        run: |
          bin/brakeman
      - name: Run rubocop
        shell: bash
        run: |
          bin/rubocop
      - name: Run rspec
        shell: bash
        run: |
          bin/rspec
      - name: Update Slack message if test is failed
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "AppBase test failed",
              "attachments": [
                {
                  "pretext": "Test finished",
                  "color": "dc3545",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Failed"
                    }
                  ]
                }
              ]
            }
      - name: Update Slack message if test is successful
        if: success()
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "AppBase test succeeded",
              "attachments": [
                {
                  "pretext": "Test finished",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Success"
                    }
                  ]
                }
              ]
            }